"""password

Revision ID: 166ac691bdab
Revises: ebe3546d0b5c
Create Date: 2024-09-05 20:53:44.570657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166ac691bdab'
down_revision = 'ebe3546d0b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
