"""promos

Revision ID: 3bf17d57be7b
Revises: 2a07bc1371b5
Create Date: 2024-09-14 23:40:10.726423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf17d57be7b'
down_revision = '2a07bc1371b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promocode_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'promocode', ['promocode_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('promocode_id')

    # ### end Alembic commands ###
