"""cascade

Revision ID: 3cb60facea71
Revises: 6c3f4d26ec0c
Create Date: 2024-09-25 13:33:54.783543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb60facea71'
down_revision = '6c3f4d26ec0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('product_description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('product_photo', sa.String(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('order_item_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_item_product_id_fkey', 'product', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('product_photo')
        batch_op.drop_column('product_description')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
