"""stripe

Revision ID: 50f4b9ba05a9
Revises: df58f6dae637
Create Date: 2024-09-08 19:42:23.509448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f4b9ba05a9'
down_revision = 'df58f6dae637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.String(), nullable=False))
        batch_op.drop_constraint('order_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['order_id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('order_username_key', ['username'])
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
