"""cascade

Revision ID: 6c3f4d26ec0c
Revises: 595461535f72
Create Date: 2024-09-25 12:53:36.957769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3f4d26ec0c'
down_revision = '595461535f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
